id: A1C3E236A
base_file: f2AEF.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:17:02.081770
  last_modified_at: 2022-06-05 20:17:02.081777
